[Image]
aspect_ratio_width = 16.0
aspect_ratio_height = 9.0
image_width = 1280

[Camera]
focal_length = 1.0
viewport_height = 2.0
camera_center = [0.0, 0.0, 0.0]
samples_per_pixel = 100

[Color]
white = [1.0, 1.0, 1.0]
blue = [0.5, 0.7, 1.0]

[[Sphere]]
center = [0.5, 0.3, -1.2]
radius = 0.5

[[Sphere]]
center = [-0.5, -0.3, -1.2]
radius = 0.5
