[Image]
aspect_ratio_width = 16.0
aspect_ratio_height = 9.0
image_width = 1280

[Camera]
v_fov = 90.0
look_from = [-2.0, 2.0, 1.0]
look_at = [0.0, 0.0, -1.0]
vup = [0.0, 1.0, 0.0]
samples_per_pixel = 64

[Color]
white = [1.0, 1.0, 1.0]
blue = [0.529, 0.808, 0.922]

[Ray]
max_depth = 20

# Sphere on the ground
[[Sphere]]
material = "lambertian"
albedo = [0.8, 0.8, 0.0]
center = [0.0, -101.0, -2.2]
radius = 100.0

# Sphere in the center
[[Sphere]]
material = "lambertian"
albedo = [0.1, 0.2, 0.5]
center = [0.0, 0.0, -2.6]
radius = 1.0

# Sphere in the left
[[Sphere]]
material = "dielectric"
refractive_index = 1.5
albedo = [0.8, 0.8, 0.8]
center = [-2.0, 0.0, -2.2]
radius = 1.0

# Sphere in the bubble
[[Sphere]]
material = "dielectric"
refractive_index = 0.66667
albedo = [0.8, 0.8, 0.8]
center = [-2.0, 0.0, -2.2]
radius = 0.5

# Sphere in the right
[[Sphere]]
material = "metal"
fuzz = 1.0
albedo = [0.8, 0.6, 0.2]
center = [2.0, 0.0, -2.2]
radius = 1.0
